# Generated by Django 3.0.1 on 2020-06-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='phoneno',
        ),
    ]
