# Generated by Django 3.0.1 on 2020-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_remove_ordermodel_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='phoneno',
            field=models.IntegerField(default=0),
        ),
    ]
